# Generated by Django 4.2 on 2023-05-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ordermodel_is_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='state',
        ),
    ]
